# Generated by Django 3.2.4 on 2021-06-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signOn', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='authoer',
            new_name='author',
        ),
    ]
